[build]
  command = "npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200